In [1]:
import time
import numpy as np
from random import randint

In [2]:
def load_dataset(data_dir=''):
    """Load the train and test examples 
    """
    x_train = np.load("data/x_train.npy")
    y_train = np.load("data/y_train.npy")
    x_test = np.load("data/x_test.npy")
    y_test = np.load("data/y_test.npy")

    return x_train, y_train, x_test, y_test

In [3]:
x_train, y_train, x_test, y_test = load_dataset()

In [4]:
#x_train, y_train = x_train[:100], y_train[:100]

In [5]:
classes, counts = np.unique(y_train, return_counts=True)

In [6]:
W = np.zeros((len(classes), x_train.shape[1]))

In [7]:
time1 = time.time()
LR = .01
num_epochs = 10
for epochs in range(num_epochs):
    #Learning rate schedule
    if (epochs > 5):
        LR = 0.001
    if (epochs > 10):
        LR = 0.0001
    if (epochs > 15):
        LR = 0.00001
    total_correct = 0
    for n in range( len(x_train)):
        n_random = randint(0,len(x_train)-1 )
        y = y_train[n_random]
        x = x_train[n_random][:]
        x = np.reshape(x, (x.shape[0],1))
        dot = np.dot(W, x)
        #print(dot)
        y_pred = np.argmax(dot)
        if y_pred != y:
            update = LR*x.T
            W[y]+=update[0]
            W[y_pred]-=update[0]
            
        if (y_pred == y):
            total_correct += 1
        
    print("Training Accuracy", total_correct/np.float(len(x_train) ) )
time2 = time.time()
print(time2-time1)

Training Accuracy 0.75156
Training Accuracy 0.78402
Training Accuracy 0.78958
Training Accuracy 0.79794
Training Accuracy 0.80124
Training Accuracy 0.79866
Training Accuracy 0.85128
Training Accuracy 0.8518
Training Accuracy 0.84866
Training Accuracy 0.84762
6.122037172317505


In [8]:
total_correct = 0
num_samples, num_classified_correctly = np.zeros((len(classes), 1)), np.zeros((len(classes), 1))
avg_accuracy = 0
conf_matrix = np.zeros((len(classes), len(classes)))
for n in range( len(x_test)):
    y = y_test[n]
    x = x_test[n][:]
    x = np.reshape(x, (x.shape[0],1))
    dot = np.dot(W, x)
    #print(dot)
    y_pred = np.argmax(dot)
    num_samples[y]+=1
    conf_matrix[y][y_pred]+=1
    if (y_pred == y):
        total_correct += 1
        num_classified_correctly[y] += 1
avg_classification_rate = total_correct/np.float(len(x_test))
avg_class_classification_rate = num_classified_correctly/num_samples
print("Avg Classification Rate", total_correct/np.float(len(x_test) ) )
print("Avg Class Classification Rate", avg_class_classification_rate )
print(conf_matrix)

Avg Classification Rate 0.8196
Avg Class Classification Rate [[0.655]
 [0.971]
 [0.59 ]
 [0.866]
 [0.775]
 [0.872]
 [0.685]
 [0.909]
 [0.916]
 [0.957]]
[[655.  13.  18.  64.  12.   1. 225.   0.  11.   1.]
 [  2. 971.   0.  17.   5.   0.   5.   0.   0.   0.]
 [ 16.   7. 590.  27. 187.   0. 166.   0.   7.   0.]
 [ 17.  27.  10. 866.  37.   0.  37.   0.   6.   0.]
 [  3.   1.  46.  50. 775.   0. 124.   0.   1.   0.]
 [  1.   1.   0.   3.   1. 872.   1.  50.  11.  60.]
 [ 76.   9.  57.  48. 112.   0. 685.   0.  13.   0.]
 [  0.   0.   0.   0.   0.  30.   0. 909.   6.  55.]
 [  4.   2.   2.  17.  10.   8.  35.   3. 916.   3.]
 [  0.   0.   0.   1.   0.  10.   0.  32.   0. 957.]]
